export const ROOM_INVENTORY = [
    {
        id: '101',
        name: '청록의 숲 (The Forest)',
        element: 'WOOD',
        features: ['편백나무 욕조', '플랜테리어', '동향 창문'],
        description: '생명력이 넘치는 나무의 기운으로 새로운 시작과 창의력을 돕는 방입니다.',
        images: ['/images/room-wood.jpg'], // Placeholder
    },
    {
        id: '102',
        name: '태양의 뜰 (The Sun)',
        element: 'FIRE',
        features: ['벽난로', '남향 테라스', 'warm 조명'],
        description: '따스한 불의 기운으로 열정과 활력을 채워주는 방입니다.',
        images: ['/images/room-fire.jpg'],
    },
    {
        id: '201',
        name: '대지의 품 (The Earth)',
        element: 'EARTH',
        features: ['황토/세라믹', '낮은 침대', '포근한 러그'],
        description: '단단한 흙의 기운으로 마음의 안정과 평화를 주는 방입니다.',
        images: ['/images/room-earth.jpg'],
    },
    {
        id: '202',
        name: '백색의 결 (The Metal)',
        element: 'METAL',
        features: ['미니멀 디자인', '메탈 오브제', '화이트 침구'],
        description: '정제된 쇠의 기운으로 결단력과 집중력을 높여주는 방입니다.',
        images: ['/images/room-metal.jpg'],
    },
    {
        id: '301',
        name: '심해의 잠 (The Ocean)',
        element: 'WATER',
        features: ['오션 뷰(또는 물소리)', '네이비 커튼', '유선형 가구'],
        description: '유연한 물의 기운으로 지혜와 깊은 휴식을 주는 방입니다.',
        images: ['/images/room-water.jpg'],
    },
];

export const WELCOME_GUIDE = {
    WOOD: {
        tea: '녹차 또는 매실차',
        teaDesc: '간의 피로를 풀고 신맛으로 기운을 모으는 차입니다.',
        aroma: '피톤치드, 파인(Pine), 유칼립투스',
        activity: '아침 일찍 일어나 숲길 산책하기, 독서, 새로운 계획 세우기',
        food: '신선한 샐러드, 신맛이 나는 과일 (사과, 키위)',
        color: '초록색, 파란색 계열',
        music: '새소리, 숲의 소리 등 자연음',
    },
    FIRE: {
        tea: '구기자차, 홍차, 커피',
        teaDesc: '심장을 튼튼하게 하고 쓴맛으로 열기를 조절하는 차입니다.',
        aroma: '로즈마리, 일랑일랑',
        activity: '햇볕 쬐기, 활동적인 운동, 사람들과 대화하기',
        food: '다크 초콜릿, 쓴맛이 나는 채소 (씀바귀)',
        color: '붉은색, 분홍색, 보라색 계열',
        music: '경쾌하고 밝은 재즈나 팝',
    },
    EARTH: {
        tea: '대추차, 칡차, 옥수수수염차',
        teaDesc: '위장을 편안하게 하고 단맛으로 긴장을 푸는 차입니다.',
        aroma: '샌달우드, 흙향',
        activity: '맨발로 흙 밟기, 도자기 만들기, 명상',
        food: '호박죽, 고구마, 단맛이 나는 뿌리 채소',
        color: '노란색, 황토색, 갈색 계열',
        music: '첼로 연주 등 중저음의 현악곡',
    },
    METAL: {
        tea: '생강차, 도라지차, 페퍼민트',
        teaDesc: '폐를 보호하고 매운맛으로 기운을 발산하는 차입니다.',
        aroma: '티트리, 사이프러스',
        activity: '정리정돈, 글쓰기, 금속 공예',
        food: '마늘, 양파, 매운맛이 나는 향신료',
        color: '흰색, 회색, 금색, 은색 계열',
        music: '피아노 독주, 맑은 종소리',
    },
    WATER: {
        tea: '둥굴레차, 흑두차(검은콩차)',
        teaDesc: '신장 기운을 돕고 짠맛(미네랄)으로 유연함을 주는 차입니다.',
        aroma: '자스민, 제라늄',
        activity: '반신욕, 물가에서 산책, 음악 감상',
        food: '해조류(미역, 김), 짠맛이 나는 음식 (적당량)',
        color: '검은색, 남색 계열',
        music: '물 흐르는 소리, 차분한 클래식',
    },
};
